version: '3'

services:
  php:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ../minwith:/var/www/html:cached

  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ../minwith:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  mail:
    build:
      context: ./docker/mail
      dockerfile: Dockerfile
    container_name: "mail"
    image: "mail"
    ports:
      - "8025:8025"

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_USER: user_mw
      MYSQL_PASSWORD: mw_pw
    volumes:
      - ./docker/mysql/db-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8888:80
    depends_on:
      - db

volumes:
  test:
    driver: local

